### ISSUE TITLE
It didn't compile in Ubuntu 12.04.

### ISSUE THREAD

**Issue by armstyle** [s3fs-fuse/s3fs-fuse#361]
I've tried to compile s3fs on Ubuntu 12.04 
root@MicroBizAppServer1:~/s3fs-fuse# uname -r
3.2.0-23-virtual
root@MicroBizAppServer1:~/s3fs-fuse# cat /etc/issue
Ubuntu 12.04.5 LTS \n \l

But it didn;t pass the make step and I got error 
root@MicroBizAppServer1:~/s3fs-fuse# make
make  all-recursive
make[1]: Entering directory `/home/ashota/s3fs-fuse'
Making all in src
make[2]: Entering directory `/home/ashota/s3fs-fuse/src'
g++ -DHAVE_CONFIG_H -I. -I..  -D_FILE_OFFSET_BITS=64 -I/usr/include/libxml2 -I/usr/include/fuse      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT s3fs.o -MD -MP -MF .deps/s3fs.Tpo -c -o s3fs.o s3fs.cpp
mv -f .deps/s3fs.Tpo .deps/s3fs.Po
g++ -DHAVE_CONFIG_H -I. -I..  -D_FILE_OFFSET_BITS=64 -I/usr/include/libxml2 -I/usr/include/fuse      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT curl.o -MD -MP -MF .deps/curl.Tpo -c -o curl.o curl.cpp
mv -f .deps/curl.Tpo .deps/curl.Po
g++ -DHAVE_CONFIG_H -I. -I..  -D_FILE_OFFSET_BITS=64 -I/usr/include/libxml2 -I/usr/include/fuse      -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -MT cache.o -MD -MP -MF .deps/cache.Tpo -c -o cache.o cache.cpp
cache.cpp: In function ‘int clock_gettime(int, timespec*)’:
cache.cpp:60:57: error: ‘int clock_gettime(int, timespec*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
/usr/include/time.h:336:12: error: previous declaration of ‘int clock_gettime(clockid_t, timespec*)’ [-fpermissive]
make[2]: *** [cache.o] Error 1
make[2]: Leaving directory `/home/ashota/s3fs-fuse/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ashota/s3fs-fuse'
make: *** [all] Error 2

The problem solved: 
./configure LIBS=-lrt 

May be we can update the README and provide right options?

**Comment by ggtakec** [comment]
@armstyle Thanks you for reporting.
I will change codes that I think s3fs should use gettimeofday function instead of clock_gettime.
Your problem is due to the gcc version, and same issue on OSX.
I merged #360, but I will change code for these problem.
Please wait a day.
Regards,

**Comment by ggtakec** [comment]
@armstyle I have to complete the verification in my test box(ubuntu12.04).
Please use latest codes.
@RobbKistler thanks again.
